[package]
name = "saturn_eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
strum_macros = "0.24"
linefeed = "0.6"
strum = "0.24"
colored = "2"